"""Add audio fields to memories

Revision ID: b338c0452179
Revises: 3833cbaa9354
Create Date: 2025-12-26 21:40:22.042042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b338c0452179'
down_revision = '3833cbaa9354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('audio_url', sa.String(length=2048), nullable=True))
    op.add_column('memories', sa.Column('audio_transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'audio_transcript')
    op.drop_column('memories', 'audio_url')
    # ### end Alembic commands ###

