"""add_recurring_tasks_support

Revision ID: dd0b605e2086
Revises: d336a0469f99
Create Date: 2025-12-05 07:09:45.315859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0b605e2086'
down_revision = 'd336a0469f99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_recurring with default False for existing rows
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=False, server_default='false'))
    # Remove server_default after column is created
    op.alter_column('tasks', 'is_recurring', server_default=None)
    
    op.add_column('tasks', sa.Column('recurrence_rule', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'recurrence_rule')
    op.drop_column('tasks', 'is_recurring')
    # ### end Alembic commands ###

