"""add_pet_games

Revision ID: 5cf19ec75515
Revises: c3f391ce0ddc
Create Date: 2025-12-26 23:04:42.425304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cf19ec75515'
down_revision = 'c3f391ce0ddc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('HAT', 'GLASSES', 'CLOTHING', 'BACKGROUND', 'EFFECT', name='itemtype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('cost_xp', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='itemrarity'), nullable=False),
    sa.Column('unlock_requirement', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(length=100), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pet_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.String(length=100), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['pet_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pet_items')
    op.drop_table('pet_items')
    # ### end Alembic commands ###

