"""add_push_notification_fields_to_users

Revision ID: 1e7ea6bde3a7
Revises: 58753d816a1b
Create Date: 2025-12-05 12:50:24.839442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7ea6bde3a7'
down_revision = '58753d816a1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('task_reminders_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('reminder_hours_before', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_hours_before')
    op.drop_column('users', 'task_reminders_enabled')
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###

