"""add_scheduled_time_to_tasks

Revision ID: d7e4b7b82b8b
Revises: f9e8d7c6b5a4
Create Date: 2025-12-04 19:44:00.088298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e4b7b82b8b'
down_revision = 'f9e8d7c6b5a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_time', sa.String(length=5), nullable=True))
    
    # Сначала заполняем NULL значения короткими уникальными временными номерами
    op.execute("""
        UPDATE users 
        SET phone_number = 'tmp' || SUBSTRING(id::text FROM 1 FOR 15)
        WHERE phone_number IS NULL
    """)
    
    # Теперь можно безопасно сделать колонку NOT NULL
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('tasks', 'scheduled_time')
    # ### end Alembic commands ###

