"""add_pet_journal

Revision ID: 71bfa4fc736f
Revises: 567d6427daaf
Create Date: 2025-12-26 23:10:08.686215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bfa4fc736f'
down_revision = '567d6427daaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

