"""add_pet_items_and_user_pet_items

Revision ID: c3f391ce0ddc
Revises: 0b7d2798ec7c
Create Date: 2025-12-26 23:00:11.335413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f391ce0ddc'
down_revision = '0b7d2798ec7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

