"""Add first_name, last_name, and avatar_url to users

Revision ID: 92697bd0e411
Revises: 1e7ea6bde3a7
Create Date: 2025-12-14 00:10:52.039242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92697bd0e411'
down_revision = '1e7ea6bde3a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subtasks_order', table_name='subtasks')
    op.drop_index('ix_subtasks_task_id', table_name='subtasks')
    op.drop_table('subtasks')
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.create_table('subtasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='subtasks_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subtasks_pkey')
    )
    op.create_index('ix_subtasks_task_id', 'subtasks', ['task_id'], unique=False)
    op.create_index('ix_subtasks_order', 'subtasks', ['task_id', 'order'], unique=False)
    # ### end Alembic commands ###

