"""Add daily_prompts table

Revision ID: 05393d6aa180
Revises: 898270001969
Create Date: 2025-12-25 23:27:44.994836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05393d6aa180'
down_revision = '898270001969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_icon', sa.String(length=10), nullable=False),
    sa.Column('category', sa.Enum('MORNING', 'DAYTIME', 'EVENING', 'WEEKLY', name='promptcategory'), nullable=False),
    sa.Column('prompt_type', sa.Enum('GRATITUDE', 'REFLECTION', 'LEARNING', 'GOAL', 'EMOTION', 'CREATIVITY', name='prompttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_prompts')
    # ### end Alembic commands ###

