"""add_subtasks_table

Revision ID: 58753d816a1b
Revises: dd0b605e2086
Create Date: 2025-12-05 07:59:27.523944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58753d816a1b'
down_revision = 'dd0b605e2086'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

