"""add_pet_social_features

Revision ID: 567d6427daaf
Revises: 5cf19ec75515
Create Date: 2025-12-26 23:07:41.845560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567d6427daaf'
down_revision = '5cf19ec75515'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

