"""Add time_capsules table

Revision ID: 898270001969
Revises: 214c329b5acb
Create Date: 2025-12-25 06:38:11.316635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898270001969'
down_revision = '214c329b5acb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_capsules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SEALED', 'OPENED', 'EXPIRED', name='capsulestatus'), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_pets_evolution_stage', table_name='pets')
    op.drop_index('ix_pets_level', table_name='pets')
    op.drop_index('ix_pets_user_id', table_name='pets')
    op.drop_constraint('pets_user_id_fkey', 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key('pets_user_id_fkey', 'pets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_pets_user_id', 'pets', ['user_id'], unique=False)
    op.create_index('ix_pets_level', 'pets', ['level'], unique=False)
    op.create_index('ix_pets_evolution_stage', 'pets', ['evolution_stage'], unique=False)
    op.drop_table('time_capsules')
    op.drop_table('subtasks')
    # ### end Alembic commands ###

