"""add_related_task_id_to_memories

Revision ID: d336a0469f99
Revises: d7e4b7b82b8b
Create Date: 2025-12-05 06:37:50.431855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd336a0469f99'
down_revision = 'd7e4b7b82b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('related_task_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'memories', 'tasks', ['related_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'related_task_id')
    # ### end Alembic commands ###

