"""Add image_url and backdrop_url to memories

Revision ID: 0a78a178c287
Revises: 001_initial
Create Date: 2025-12-03 09:53:38.679222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a78a178c287'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_embeddings_vector', table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('memories', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('memories', sa.Column('backdrop_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'backdrop_url')
    op.drop_column('memories', 'image_url')
    op.create_index('ix_embeddings_vector', 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###

