"""add_new_pet_types_and_mutations

Revision ID: 0b7d2798ec7c
Revises: b338c0452179
Create Date: 2025-12-26 22:53:59.036979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7d2798ec7c'
down_revision = 'b338c0452179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_shiny', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('pets', sa.Column('mutation_type', sa.String(length=50), nullable=True))
    op.add_column('pets', sa.Column('special_effect', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'special_effect')
    op.drop_column('pets', 'mutation_type')
    op.drop_column('pets', 'is_shiny')
    # ### end Alembic commands ###

