"""add_color_and_icon_to_tasks

Revision ID: 8b45c299cebc
Revises: def9ca32375f
Create Date: 2026-01-08 11:25:59.180969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b45c299cebc'
down_revision = 'def9ca32375f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('tasks', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'icon')
    op.drop_column('tasks', 'color')
    # ### end Alembic commands ###

